name: CI

on:                                       #this section defines the events that will trigger the workflow. in this case, the workflow will run on push to the main branch, on pull requests, and when manually triggered using workflow_dispatch.
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: '0 0 * * *'                    #this will run the workflow every day at midnight. you can change the cron expression to run it at a different time or frequency.
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'sit'
        type: choice
        options:
          - sit
          - uat
      suite:
        description: 'Test suite to run'
        required: true
        default: 'smoke'
        type: choice
        options:
          - all
          - smoke

concurrency:
  group: ci-${{ github.ref }}               #this will create a unique concurrency group for each branch. so if you have multiple branches, they will not cancel each other.
  cancel-in-progress: true                  #this will cancel any in-progress runs of the same concurrency group. so if you push multiple commits to the same branch, only the latest one will run.

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build app
        run: npm run build

  test_unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install deps
        run: npm ci
      - name: Run Vitest
        run: npx vitest run --reporter=verbose 

  test_integration:
    name: Integration Tests (${{github.event.inputs.suite || 'smoke' }} / ${{github.event.inputs.environment || 'all' }})     #this is just a name for the job.
    runs-on: ubuntu-latest              #runs on github-hosted ubuntu-latest runner. not docker container.
    needs: build                        #this job will only run if the 'build' job is successful.
    steps:
      - uses: actions/checkout@v4       #checkout the code from the repository. this is mandatory for every job that needs to access the codebase.
      - uses: actions/setup-node@v4     #setup node.js environment.
        with:
          node-version: 22              #specify the node.js version to use.
      - name: Install dependencies      #install the project dependencies using npm ci command.
        run: npm ci
      - name: Install Playwright Browsers  #install the necessary browsers for Playwright testing.
        run: npx playwright install --with-deps
      - name: Run Playwright Tests      #run the integration tests using Playwright.
        run: npx playwright test
      - uses: actions/upload-artifact@v4  #upload the test results as an artifact. this is useful for debugging failed tests.
        if: ${{ !cancelled() }}  #this will only upload the artifact if the job was not cancelled. this is useful for debugging failed tests.
        with:
          name: Integration Test (Playwright)
          path: reports-e2e/html/   #this is the path to the directory where the test results are stored. this is relative to the root of the repository. this is where playwright will output the test results in html format.
          if-no-files-found: error  #this will cause the job to fail if the artifact is not found. this is useful for debugging failed tests.

  deploy:
    name: Deploy (mock)
    runs-on: ubuntu-latest
    needs: [test_unit, test_integration]       #this job will only run if the 'test_unit' and 'test_integration' jobs are successful.
    container:
      image: alpine:latest
    steps:
      - name: Mock deployment
        run: echo 'Mock deployment was successful!'
  
  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: deploy
    container:
      image: mcr.microsoft.com/playwright:v1.54.2-jammy  #the version has to be exactly the same as in the package.json file.
      options: --user 1001      # this allows firefox create a profile directory in the container. 1001 is the user id of the default user in the container. without this, firefox will fail to run with an error about not being able to create a profile directory.
    env:
      E2E_BASE_URL: https://spanish-cards.netlify.app
      USERNAME: ${{ secrets.USERNAME }}
    steps:                      #since we are using docker image, we don't need to setup node.js and playwright browsers. they are already included in the image. we just need to install the dependencies and run the tests.
      - uses: actions/checkout@v4
      - name: Install deps
        run: npm ci
      - name: Run Playwright E2E
        run: npx playwright test
      - name: Echo
        run: echo ${{ USERNAME }}
